### ISSUE TITLE
Several issues while trying to run

### ISSUE THREAD

**Issue by DomtronVox** [rogue-craft/rogue-craft#1]
Hi. Ran across your game and thought I would try it since I love crafting, roguelikes, and development. However, couldn't get it to run. Using Ubuntu 16.04.

I am getting several issues with the program trying to access directories that haven't been created yet. The first one was easy enough to fix with a mkdir -p. 
`~/.rogue-craft/environments/.env.prod`

However, I'm stuck at the second one since it is printing null for the directory path and do not have time to dig into the source atm to find the issue.
`[src/storage/storage.c:9:dir_create]Unable to create directory [(null)] - [errno] - Bad address`

Hope this info helps you.

**Comment by Isty001** [comment]
Hi,

Thanks for reporting this issue. How did you try to install? The problem is that an environment variable is not set as I assume you `touch`ed the `.env.prod` file, and `getenv` returns `NULL`.  I tried to remove all files, and remove from both source, and a tar, and it seems to work for me on 64 bit Ubuntu 14.04.  

Could you please give a bit more information, and execute the following commands in a terminal, and post the outputs?
`uname -a`
`ls -la ~/.rogue-craft`

**Comment by Isty001** [comment]
Please let me know if you still have installation issues.
